In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import torchvision
from torchvision.datasets import MNIST
import torchvision.transforms as transforms
import numpy as  np
import torch.nn.functional as F
import torch.nn as nn 

In [ ]:
a = torch.tensor([[1,2],
                  [3,4]])
                  
b = torch.tensor([[5,6],
                  [7,8]])
c = a@b #For dot product
print(c)

d = a*b #For elementwise multiplication 
print(d)
print(c)

#in numpy it is used np.dot
'''
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]
'''

In [1]:
import torch
a=torch.tensor([[5,9],
                [2,6],
                [2,3]]) # 3x2 

b=torch.rand(3,2)
x=torch.tensor([[5,9,4],
                [2,6,5],
                      ]) # 2x3 

elementwise = a*b    # element wise multiplication =3x2
dotproduct  = a@x     # dot product     3x2  2x3 =3x3
print(f'\n elementwise a,b \n',elementwise)
print(f'\n dotproduct a,x \n=',dotproduct)

c=torch.cat((a,b),dim=0)
print(f'concatinating a and b in axis 0\n',c)
d=torch.cat((a,b),dim=1)
print(f'\nconcatinating a and b in axis 1\n',d)

print("a : {}".format(a))

slice_a= a[:,0]   # tensor([9, 6, 3])
print(f' \n slicing a[:,0] = ',slice_a.shape)
slice_a_keep_dim=a[:,0:1]
print(f' :\n slice_a_keep_dim a[:, 0:1] = ',slice_a_keep_dim.shape)

#Converting 
convert_numpy = a.numpy()
convert_torch = torch.from_numpy(convert_numpy)
type(convert_numpy), type(convert_torch)

#sum for each of dim
print(a)
print(a.shape)
sum=a.sum()
print(f'\nsum =', sum)
sum_axis_keep_dim=a.sum(dim=1,keepdim=True)
sum_axis=a.sum(dim=0)
print(f'\nsum and keep dim =',sum_axis_keep_dim)
print(f'\nsum and keep dim =',sum_axis)





#mean for each of dim ---------------------------------------------------
#mean_column_of_a=torch.mean(a,axis=0)
np_a=np.array([[1, 2, 3, 4], 
            [3, 4, 5, 10]])
print(np.mean(np_a,axis=1))

tensor_a=torch.tensor([[1, 2, 3, 4], 
            [3, 4, 5, 10]],dtype=torch.float)

print(torch.mean(tensor_a,dim=1))


 elementwise a,b 
 tensor([[3.1748, 3.9220],
        [1.0424, 0.2190],
        [0.8258, 1.0702]])

 dotproduct a,x 
= tensor([[43, 99, 65],
        [22, 54, 38],
        [16, 36, 23]])
concatinating a and b in axis 0
 tensor([[5.0000, 9.0000],
        [2.0000, 6.0000],
        [2.0000, 3.0000],
        [0.6350, 0.4358],
        [0.5212, 0.0365],
        [0.4129, 0.3567]])

concatinating a and b in axis 1
 tensor([[5.0000, 9.0000, 0.6350, 0.4358],
        [2.0000, 6.0000, 0.5212, 0.0365],
        [2.0000, 3.0000, 0.4129, 0.3567]])
a : tensor([[5, 9],
        [2, 6],
        [2, 3]])
 
 slicing a[:,0] =  torch.Size([3])
 :
 slice_a_keep_dim a[:, 0:1] =  torch.Size([3, 1])
tensor([[5, 9],
        [2, 6],
        [2, 3]])
torch.Size([3, 2])

sum = tensor(27)

sum and keep dim = tensor([[14],
        [ 8],
        [ 5]])

sum and keep dim = tensor([ 9, 18])


NameError: name 'np' is not defined