In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import torchvision
from torchvision.datasets import MNIST
import torchvision.transforms as transforms
import numpy as  np
import torch.nn.functional as F
import torch.nn as nn 

In [2]:
a = torch.tensor([[1,2],
                  [3,4]])
                  
b = torch.tensor([[5,6],
                  [7,8]])
c = a@b #For dot product
print(c)

d = a*b #For elementwise multiplication 
print(d)
print(c)

# dot product in NUmpy ?

tensor([[19, 22],
        [43, 50]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[19, 22],
        [43, 50]])


In [13]:
import torch
a=torch.tensor([[5,9],
                [2,6],
                [2,3]]) # 3x2 
"""
b=torch.rand(3,2)
x=torch.tensor([[5,9,4],
                [2,6,5],
                      ]) # 2x3 

elementwise = a*b    # element wise multiplication =3x2
dotproduct  = a@x     # dot product     3x2  2x3 =3x3
print(f'\n elementwise a,b \n',elementwise)
print(f'\n dotproduct a,x \n=',dotproduct)

c=torch.cat((a,b),dim=0)
print(f'concatinating a and b in axis 0\n',c)
d=torch.cat((a,b),dim=1)
print(f'\nconcatinating a and b in axis 1\n',d)

"""

print("a : {}".format(a))

slice_a= a[:,0]   # tensor([9, 6, 3])
print(f' \n slicing a[:,0] = ',slice_a.shape)

slice_a_keep_dim=a[:,0:1]
print(f' :\n slice_a_keep_dim a[:, 0:1] = ',slice_a_keep_dim.shape)

print((slice_a @ slice_a))
'''
sum=a.sum()
print(f'\nsum =', sum)

sum_axis_keep_dim=a.sum(dim=1,keepdim=True)
sum_axis=a.sum(dim=0)
print(f'\nsum and keep dim =',sum_axis)
print(f'\nsum and keep dim =',sum_axis_keep_dim)

#Converting 
convert_numpy = a.numpy()
convert_torch = torch.from_numpy(convert_numpy)
type(convert_numpy), type(convert_torch)

k=torch.arange(10)
print(f"k=",k)'''

a : tensor([[5, 9],
        [2, 6],
        [2, 3]])
 
 slicing a[:,0] =  torch.Size([3])
 :
 slice_a_keep_dim a[:, 0:1] =  torch.Size([3, 1])
tensor(33)


'\nsum=a.sum()\nprint(f\'\nsum =\', sum)\n\nsum_axis_keep_dim=a.sum(dim=1,keepdim=True)\nsum_axis=a.sum(dim=0)\nprint(f\'\nsum and keep dim =\',sum_axis)\nprint(f\'\nsum and keep dim =\',sum_axis_keep_dim)\n\n#Converting \nconvert_numpy = a.numpy()\nconvert_torch = torch.from_numpy(convert_numpy)\ntype(convert_numpy), type(convert_torch)\n\nk=torch.arange(10)\nprint(f"k=",k)'