In [15]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import torchvision
from torchvision.datasets import MNIST
import torchvision.transforms as transforms
import torch.nn.functional as F
import torch.nn as nn 

**Train_Loder and iterating images into it**

In [ ]:
# Loading data
transform = ToTensor()

train_set = MNIST(root='./../datasets', train=True, download=True, transform=transform)
test_set = MNIST(root='./../datasets', train=False, download=True, transform=transform)

train_loader = DataLoader(train_set, shuffle=True, batch_size=128)

In [17]:
for image_and_target in train_loader: 
    image_and_target.append(image)

print(image_and_target[0].shape)  #shows one batch in the list which consist of image and target

In [ ]:
for batch in train_loader:
    images, targets = batch 

plt.imshow(images[0].squeeze())      #1x28x28--> 28x28

In [ ]:
from matplotlib import pyplot as plt
images, labels = next(iter(train_loader))   #taking one by one batches  
print(images.shape)
plt.imshow(images[0].squeeze())             #1x28x28--> 28x28

**How to use dim in softmax**

In [ ]:
import torch
import torch.nn.functional as F

x = torch.tensor([[1,2],[3,4]],dtype=torch.float)
F.softmax(x,dim=0)
#x=tensor([[0.1192, 0.1192],
  #        [0.8808, 0.8808]])
F.softmax(x,dim=1)  # or F.softmax(x,dim=-1)
#tensor([[0.2689, 0.7311],
  #      [0.2689, 0.7311]])


join(concatenate) tensors in the 0 dimension
tensor([[1., 2.],
        [3., 4.],
        [0., 3.],
        [4., 1.],
        [4., 3.],
        [2., 5.]])
torch.Size([6, 2])

 join(concatenate) tensors in the -1 dimension
tensor([[1., 2., 0., 3., 4., 3.],
        [3., 4., 4., 1., 2., 5.]])
torch.Size([2, 6])

Join (stack)tensors in the 0 dimension
tensor([[[1., 2.],
         [3., 4.]],

        [[0., 3.],
         [4., 1.]],

        [[4., 3.],
         [2., 5.]]])
torch.Size([3, 2, 2])

Join(stack) tensors in the -1 dimension
tensor([[[1., 0., 4.],
         [2., 3., 3.]],

        [[3., 4., 2.],
         [4., 1., 5.]]])
torch.Size([2, 2, 3])
