In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import torchvision
from torchvision.datasets import MNIST
import torchvision.transforms as transforms
import torch.nn.functional as F
import torch.nn as nn 

In [1]:
import torch

# create tensors
T1 = torch.Tensor([[1,2],[3,4]])
T2 = torch.Tensor([[0,3],[4,1]])
T3 = torch.Tensor([[4,3],[2,5]])

print("\njoin(concatenate) tensors in the 0 dimension")
T = torch.cat((T1,T2,T3), 0)   # OUTPUT : 6x2
print(T)
print(T.shape) 

print("\n join(concatenate) tensors in the -1 dimension")
T = torch.cat((T1,T2,T3), -1)  # OUTPUT : 2x6
print(T)
print(T.shape)

print("\nJoin (stack)tensors in the 0 dimension")
T = torch.stack((T1,T2,T3), 0)  # OUTPUT : 3x2x2
print(T)
print(T.shape)

print("\nJoin(stack) tensors in the -1 dimension")
T = torch.stack((T1,T2,T3), -1)  # OUTPUT : 2x2x3
print(T)
print(T.shape)


join(concatenate) tensors in the 0 dimension
tensor([[1., 2.],
        [3., 4.],
        [0., 3.],
        [4., 1.],
        [4., 3.],
        [2., 5.]])
torch.Size([6, 2])

 join(concatenate) tensors in the -1 dimension
tensor([[1., 2., 0., 3., 4., 3.],
        [3., 4., 4., 1., 2., 5.]])
torch.Size([2, 6])

Join (stack)tensors in the 0 dimension
tensor([[[1., 2.],
         [3., 4.]],

        [[0., 3.],
         [4., 1.]],

        [[4., 3.],
         [2., 5.]]])
torch.Size([3, 2, 2])

Join(stack) tensors in the -1 dimension
tensor([[[1., 0., 4.],
         [2., 3., 3.]],

        [[3., 4., 2.],
         [4., 1., 5.]]])
torch.Size([2, 2, 3])
